### ISSUE TITLE
The requested accessory 'sonos' was not registered by any plugin.

### ISSUE THREAD

**Issue by Juljoo** [nfarina/homebridge-sonos#20]
Hi,

i get this massage when i want to start homebridge on my raspberrypi2:

`/usr/local/lib/node_modules/homebridge/lib/api.js:47
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'sonos' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:47:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:166:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:38:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)`

My Config:
`{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "platforms": [
        {
            "platform" : "Symcon",
            "name" : "Symcon",
            "rpcClientOptions": {
                "port": 3777,
                "host": "127.0.0.1",
                "path": "/api/",
                "login": "username",
                "hash": "clear text password",
                "strict": true
            }
        },
        {
                "platform": "HarmonyHub",
                "name": "Wohnzimmer Harmony Hub"
        }
  ],
"accessories": [
    {
      "accessory": "Sonos",
      "name": "Bedroom Speakers",
      "room": "Bedroom"
    }
  ]
}
`

**Comment by BrekiTomasson** [comment]
Did you install the plugin properly? Try to `sudo npm install -g homebridge-sonos` and restart the homebridge service.

**Comment by pickerin** [comment]
It's 'Sonos', the capitalization is important.  Your config shows it correctly, but the error you're receiving shows it as lowercase.  Make sure you're using the config.json you think you are...
