### ISSUE TITLE
Homebridge crashes after several hours

### ISSUE THREAD

**Issue by matthiasdebaat** [nfarina/homebridge-sonos#48]
I use this great homebridge plugin and it works pretty neat! But after some hours my whole homebridge crashes. I think this plugin is the reason. The following is from my error log:
> Error: connect ETIMEDOUT 192.168.2.7:1400
>     at Object.exports._errnoException (util.js:1022:11)
>     at exports._exceptionWithHostPort (util.js:1045:20)
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

Is there a fix for this?

**Comment by roe1974** [comment]
same problem here....

**Comment by soomrox** [comment]
I am having the same issue. The system crashed and I have to restart.
This only started after install the homebridge-sonos plugin. If I remove it I have no crash.

Mainly I get the following error 
                                                                                       
events.js:136                                                                                                                                            
      throw er; // Unhandled 'error' event                                                                                                               
      ^                                                                                                                                                  
                                                                                                                                                         
Error: socket hang up                                                                                                                                    
    at createHangUpError (_http_client.js:330:15)                                                                                                        
    at Socket.socketOnEnd (_http_client.js:423:23)                                                                                                       
    at Socket.emit (events.js:164:20)                                                                                                                    
    at endReadableNT (_stream_readable.js:1054:12)                                                                                                       
    at _combinedTickCallback (internal/process/next_tick.js:138:11)                                                                                      
    at process._tickCallback (internal/process/next_tick.js:180:9)          


Please can someone help

**Comment by villevirtanen** [comment]
I can easily reproduce Homebridge to crash just by disconnecting one of my Sonos speakers. That causes Homebridge crash everytime. I do not have log available at the moment but maybe that could be a reason?
