### ISSUE TITLE
Homebridge Startup error After adding speaker

### ISSUE THREAD

**Issue by joystick666** [nfarina/homebridge-sonos#5]
Error at the end of Startup

login as: pi
pi@192.168.178.12's password:

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Dec 16 18:17:40 2015
pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Loaded plugin: homebridge-fibaro-hc2
Registering platform 'homebridge-fibaro-hc2.FibaroHC2'
---
Loaded plugin: homebridge-sonos
Registering accessory 'homebridge-sonos.Sonos'
---
Loaded config.json with 1 accessories and 1 platforms.
---
Loading 1 platforms...
[FibaroHC2] Initializing FibaroHC2 platform...
[FibaroHC2] Fetching Fibaro Home Center devices...
Loading 1 accessories...
[Bedroom Speakers] Initializing Sonos accessory...
[Bedroom Speakers] Found a playable device at 192.168.178.34 for room 'Kinderzimmer'
[FibaroHC2] Found: com.fibaro.device
[FibaroHC2] Found: HC_user
[FibaroHC2] Found: weather
[FibaroHC2] Found: com.fibaro.ipCamera
[FibaroHC2] Found: com.fibaro.ipCamera
[FibaroHC2] Found: com.fibaro.ipCamera
[FibaroHC2] Found: HC_user
[FibaroHC2] Found: virtual_device
[FibaroHC2] Found: com.fibaro.thermostatDanfoss
[FibaroHC2] Found: com.fibaro.thermostatDanfoss
[FibaroHC2] Found: com.fibaro.thermostatDanfoss
[FibaroHC2] Found: com.fibaro.thermostatDanfoss
[FibaroHC2] Found: com.fibaro.thermostatDanfoss
[FibaroHC2] Found: com.fibaro.FGWP101
[FibaroHC2] Found: com.fibaro.binarySwitch
[FibaroHC2] Found: com.fibaro.binarySwitch
[FibaroHC2] Found: com.fibaro.binarySwitch
[FibaroHC2] Found: com.fibaro.binarySwitch
[FibaroHC2] Found: com.fibaro.binarySwitch
[FibaroHC2] Found: com.fibaro.binarySwitch
[FibaroHC2] Found: iOS_device
[FibaroHC2] Found: com.fibaro.thermostatDanfoss
[FibaroHC2] Found: com.fibaro.doorSensor
[FibaroHC2] Found: com.fibaro.binarySensor
[FibaroHC2] Found: com.fibaro.temperatureSensor
[FibaroHC2] Found: com.fibaro.doorSensor
[FibaroHC2] Found: com.fibaro.binarySensor
[FibaroHC2] Found: com.fibaro.temperatureSensor
[FibaroHC2] Found: com.fibaro.FGMS001
[FibaroHC2] Found: com.fibaro.temperatureSensor
[FibaroHC2] Found: com.fibaro.lightSensor
[FibaroHC2] Found: com.fibaro.doorSensor
[FibaroHC2] Found: com.fibaro.binarySensor
[FibaroHC2] Found: com.fibaro.temperatureSensor
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.seismometer
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.wakeOnLan
[FibaroHC2] Found: iOS_device
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.FGWP101
[FibaroHC2] Found: HC_user
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.thermostatDanfoss
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.binarySwitch
[FibaroHC2] Found: com.fibaro.binarySwitch
[FibaroHC2] Found: com.fibaro.binarySwitch
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.binarySwitch
[FibaroHC2] Found: com.fibaro.binarySwitch
[FibaroHC2] Found: com.fibaro.binarySwitch
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.binarySwitch
[FibaroHC2] Found: com.fibaro.binarySwitch
[FibaroHC2] Found: com.fibaro.binarySwitch
[FibaroHC2] Found: com.fibaro.ipCamera
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.thermostatDanfoss
[FibaroHC2] Found: virtual_device
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.remoteController
[FibaroHC2] Found: virtual_device
[FibaroHC2] Found: virtual_device
[FibaroHC2] Found: virtual_device
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.doorSensor
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.binarySwitch
[FibaroHC2] Found: com.fibaro.binarySwitch
[FibaroHC2] Found: com.fibaro.binarySwitch
[FibaroHC2] Found: com.fibaro.binarySwitch
[FibaroHC2] Found: com.fibaro.binarySwitch
[FibaroHC2] Found: com.fibaro.binarySwitch
[FibaroHC2] Found: com.fibaro.binarySwitch
[FibaroHC2] Found: virtual_device
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.FGWP101
[FibaroHC2] Found: iOS_device
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.motionSensor
[FibaroHC2] Found: com.fibaro.temperatureSensor
[FibaroHC2] Found: com.fibaro.lightSensor
[FibaroHC2] Found: com.fibaro.humiditySensor
[FibaroHC2] Found: iOS_device
[FibaroHC2] Found: iOS_device
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.multilevelSwitch
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.FGWP101
[FibaroHC2] Found: com.fibaro.voipUser
[FibaroHC2] Found: com.fibaro.philipsHue
[FibaroHC2] Found: com.fibaro.philipsHueLight
[FibaroHC2] Found: com.fibaro.philipsHueLight
[FibaroHC2] Found: com.fibaro.philipsHueLight
[FibaroHC2] Found: com.fibaro.zwaveDevice
[FibaroHC2] Found: com.fibaro.multilevelSwitch
[FibaroHC2] Found: com.fibaro.multilevelSwitch
[FibaroHC2] Found: com.fibaro.multilevelSwitch
[FibaroHC2] Found: virtual_device
[FibaroHC2] Initializing platform accessory 'WOL'...
[FibaroHC2] Initializing platform accessory 'Kühlschrank'...
[FibaroHC2] Initializing platform accessory 'Schrank links'...
[FibaroHC2] Initializing platform accessory 'Schrank links2'...
[FibaroHC2] Initializing platform accessory 'Schrank rechts'...
[FibaroHC2] Initializing platform accessory 'Schrank rechts 2'...
[FibaroHC2] Initializing platform accessory 'Türkontakt Vorne'...
[FibaroHC2] Initializing platform accessory 'Temp. Tür Vorne'...
[FibaroHC2] Initializing platform accessory 'Küchenfenster'...
[FibaroHC2] Initializing platform accessory 'Temp Küche'...
[FibaroHC2] Initializing platform accessory 'Bewegung'...
[FibaroHC2] Initializing platform accessory 'Temperatur'...
[FibaroHC2] Initializing platform accessory 'Helligkeit'...
[FibaroHC2] Initializing platform accessory 'Türkontakt'...
[FibaroHC2] Initializing platform accessory 'Temp hinten'...
[FibaroHC2] Initializing platform accessory 'Waschmaschine'...
[FibaroHC2] Initializing platform accessory 'Fassade'...
[FibaroHC2] Initializing platform accessory 'Fassade hinten n/a'...
[FibaroHC2] Initializing platform accessory 'Fassade seite'...
[FibaroHC2] Initializing platform accessory 'Fassade unbenutzt'...
[FibaroHC2] Initializing platform accessory 'Türöffner'...
[FibaroHC2] Initializing platform accessory 'Türöffner n/a'...
[FibaroHC2] Initializing platform accessory 'iphone'...
[FibaroHC2] Initializing platform accessory '-Roomba-'...
[FibaroHC2] Initializing platform accessory 'Küche'...
[FibaroHC2] Initializing platform accessory 'Deckenlampe'...
[FibaroHC2] Initializing platform accessory 'Loggia Tür'...
[FibaroHC2] Initializing platform accessory '246.0'...
[FibaroHC2] Initializing platform accessory 'Playstation'...
[FibaroHC2] Initializing platform accessory 'Mediacenter'...
[FibaroHC2] Initializing platform accessory 'Subwoofer'...
[FibaroHC2] Initializing platform accessory 'HDMI Switch'...
[FibaroHC2] Initializing platform accessory 'Receiver'...
[FibaroHC2] Initializing platform accessory 'TV'...
[FibaroHC2] Initializing platform accessory 'Zuhause status'...
[FibaroHC2] Initializing platform accessory 'Fensterbeleuchtung'...
[FibaroHC2] Initializing platform accessory 'Bewegung'...
[FibaroHC2] Initializing platform accessory 'Temeratur'...
[FibaroHC2] Initializing platform accessory 'Helligkeit'...
[FibaroHC2] Initializing platform accessory 'Stehlampe'...
[FibaroHC2] Initializing platform accessory 'Blumenlampe'...
[FibaroHC2] Initializing platform accessory 'Wandschalter'...
[FibaroHC2] Initializing platform accessory 'blink steckdose'...
Scan this code with your HomeKit App on your
Homebridge is running on port 51826.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:58:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:132:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:347:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:50:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:220:14)
pi@raspberrypi:~ $
pi@raspberrypi:~ $

**Comment by NovaGL** [comment]
It's saying "Error: listen EADDRINUSE :::51826" check that you don't have any node applications running on that address. Restart your Pi and try again

**Comment by adamstephenson** [comment]
I think you might have setup homebridge to autostart in init.d and you're attempting to run it again manually. I'm just starting at this, but that happened to me earlier today.
