### ISSUE TITLE
Homebridge crashes after start up

### ISSUE THREAD

**Issue by Jasperschn** [nfarina/homebridge-sonos#63]
I hope someone can help me out with this code. After installing the plugin and updating the config.json file, when I start homebridge I get the following code:

[2018-12-17 21:36:51] Homebridge is running on port 37017.
[2018-12-17 21:36:51] [Woonkamer Speakers] Found a playable device at 192.168.178.17 for room 'Tv-kamer'
[2018-12-17 21:36:51] [Woonkamer Speakers] Found a playable device at 192.168.178.21 for room 'Tv-kamer'
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at Socket._healthCheck (dgram.js:598:11)
    at Socket.close (dgram.js:491:8)
    at Search.destroy (/usr/local/lib/node_modules/homebridge-sonos/node_modules/sonos/lib/sonos.js:1089:15)
    at SonosAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-sonos/index.js:187:16)
    at /usr/local/lib/node_modules/homebridge-sonos/node_modules/sonos/lib/sonos.js:764:7
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-sonos/node_modules/xml2js/lib/xml2js.js:483:18)
    at emitOne (events.js:115:13)
    at Parser.emit (events.js:210:7)
    at SAXParser.onclosetag (/usr/local/lib/node_modules/homebridge-sonos/node_modules/xml2js/lib/xml2js.js:444:26)
    at emit (/usr/local/lib/node_modules/homebridge-sonos/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/local/lib/node_modules/homebridge-sonos/node_modules/sax/lib/sax.js:629:5)

**Comment by Jasperschn** [comment]
Sorry, i did the update command at it works. But after i changed the config.jsof file it crashes again. Did the update and the problem is solved. 

So it seems like i have to do the update every time i change the config file.

**Comment by leoneleone** [comment]
@Jasperschn 
which update do you mean?
can you what console command you used?

I'm having the same problem and can't solve it :(

**Comment by Jasperschn** [comment]
@leoneleone I did the:
 sudo npm install -g homebridge-sonos@latest

It worked for me
